// 3_Frontend/react/src/components/Home.js
import { React, useState, useEffect } from "react";
import Clock from "./DigitalClock";

const homeStyles = {
    bgHome: {
        backgroundImage: 'url("/assets/imgs/background.png")',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
        position: 'relative',
        height: '100%',
        width: '100%',
    },
    bgText: {
        color: 'white',
        fontSize: '40px',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: 2,
    },
}


function Home() {
    const [time, setTime] = useState(""); // 用于显示时间的状态
    const [displayClock, setDisplayClock] = useState(true); // 控制时钟是否显示的状态

    useEffect(() => {
        // 初始化时钟显示
        updateClockDisplay(window.innerWidth);

        // 开始显示时间
        showTime();

        // 当窗口大小发生变化时，更新时钟显示
        const handleResize = () => {
            updateClockDisplay(window.innerWidth);
        };

        window.addEventListener("resize", handleResize);

        return () => {
            // 清除resize事件监听
            window.removeEventListener("resize", handleResize);
        };
    }, []);

    // 更新时钟显示的方法
    const updateClockDisplay = (width) => {
        setDisplayClock(width >= 768);
    };

    // 时钟逻辑
    const showTime = () => {
        setInterval(() => {
            const date = new Date();
            let hours = date.getHours();
            let minutes = date.getMinutes();
            let seconds = date.getSeconds();

            hours = hours < 10 ? "0" + hours : hours;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            const currentTime = `${hours}:${minutes}:${seconds}`;

            // 使用setTime更新时间
            setTime(currentTime);
        }, 1000);
    };

    return (
        <div style={homeStyles.bgHome}>
            <div style={homeStyles.bgText}>
                <h1>Hey, here you are!</h1>
                <p>NECESSITAS EST INGENII MATER!</p>
                {/*<div className="container">*/}
                {/*    <div className="d-grid gap-2 d-md-flex justify-content-md-center">*/}
                {/*        <a href="./catalog.html" className="btn btn-primary me-md-2" type="button">*/}
                {/*            Learn More*/}
                {/*        </a>*/}
                {/*    </div>*/}
                {/*</div>*/}
            </div>

            <Clock /> {/* Use the Clock component */}
        </div>
    );
}

export default Home;

// 3_Frontend/angular/src/app/home/home.component.ts
import {Component, HostListener, NgZone, OnInit} from '@angular/core';
import {CommonModule} from "@angular/common";
import {Event, NavigationError} from "@angular/router";

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements OnInit {
  public time: string; // 用于显示时间的属性
  public displayClock: boolean; // 控制时钟是否显示

  constructor(private ngZone: NgZone) {
    this.displayClock = true; // 默认显示时钟
    this.time = ''; // 初始化时间字符串
  }

  ngOnInit(): void {
    this.updateClockDisplay(window.innerWidth);
    this.showTime();
  }

  // 当窗口大小发生变化时调用
  @HostListener('window:resize', ['$event'])
  onResize(event: Event) {
    // 获取窗口变化后的宽度
    if (event instanceof NavigationError) {
      // @ts-ignore
      const width = event.target['innerWidth'];
      // 更新时钟显示
      this.updateClockDisplay(width);
    }
  }

  // 更新时钟显示的方法
  updateClockDisplay(width: number) {
    this.displayClock = width >= 768;
  }

  // 时钟逻辑
  showTime() {
    this.ngZone.runOutsideAngular(() => {
      setInterval(() => {
        const date = new Date();
        let hours: string | number = date.getHours();
        let minutes: string | number = date.getMinutes();
        let seconds: string | number = date.getSeconds();

        hours = hours < 10 ? '0' + hours : hours;
        minutes = minutes < 10 ? '0' + minutes : minutes;
        seconds = seconds < 10 ? '0' + seconds : seconds;

        // 输出时间到控制台以验证其是否正在更新
        // console.log(this.time);

        // 使用NgZone确保视图可以更新
        this.ngZone.run(() => {
          this.time = `${hours}:${minutes}:${seconds}`;
          // this.cdr.detectChanges(); // 强制执行变更检测
        });
      }, 1000);
    });
  }
}

<!--<p>home works!</p>-->

<div class="bg-home">

  <!-- White text floating in the middle of the screen -->
  <div class="bg-text" style="color: white; font-size: 40px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 2;">
    <h1>Hey, here you are!</h1>
    <p>NECESSITAS EST INGENII MATER!</p>

    <!-- This is the button, in the middle of the screen -->
    <div class="container">
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <!-- The button will link to the projects page -->
        <a href="./catalog.html" class="btn btn-primary me-md-2" type="button">Learn More</a>
      </div>
    </div>
  </div>


  <!-- Display a clock in the bottom right corner -->
  <div *ngIf="displayClock" id="MyClockDisplay" class="clock">
    {{ time }}
  </div>

</div>
